Repository scientific-python/blog.scientific-python.org, pull requests merged in 2022-06, with the labels that each got.

#70 Fix tags on latest posts
  content/posts/matplotlib/how-to-create-custom-tables/index.md
  content/posts/numpy/mukulikapahari/index.md
Labels: maintenance

#73 Fix CI on SciPy article
  content/posts/scipy/internships/smit/index.md
Labels: bug, maintenance

#71 Add alt text to blog posts
  content/posts/matplotlib/GSoC_2021_PreQuarter/index.md
  content/posts/matplotlib/animated-fractals/index.md
  content/posts/matplotlib/custom-3d-engine/index.md
  content/posts/matplotlib/draw-all-graphs-of-n-nodes/index.md
  content/posts/matplotlib/emoji-mosaic-art/index.md
  content/posts/matplotlib/matplotlib-in-data-driven-seo/index.md
  content/posts/matplotlib/mpl-for-making-diagrams/index.md
  content/posts/matplotlib/pyplot-vs-object-oriented-interface/index.md
  content/posts/matplotlib/using-matplotlib-to-advocate-for-postdocs/index.md
  content/posts/matplotlib/visualising-usage-using-batteries/index.md
  content/posts/matplotlib/warming-stripes/index.md
Labels: matplotlib, accepted
